# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 02:11
from __future__ import unicode_literals

import azanlocator.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField(default=django.utils.timezone.now)),
                ('subuh', models.TimeField(default=datetime.time(6, 0))),
                ('syuruk', models.TimeField(default=datetime.time(6, 0))),
                ('zuhur', models.TimeField(default=datetime.time(6, 0))),
                ('asar', models.TimeField(default=datetime.time(6, 0))),
                ('maghrib', models.TimeField(default=datetime.time(6, 0))),
                ('isha', models.TimeField(default=datetime.time(6, 0))),
            ],
        ),
        migrations.CreateModel(
            name='EsolatZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='KUALA LUMPUR', max_length=30)),
                ('zone_name', models.CharField(default='Kuala Lumpur', max_length=30)),
                ('code_name', models.CharField(default='SGR03', max_length=20)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subuh', models.TimeField(default=datetime.time(6, 0))),
                ('syuruk', models.TimeField(default=datetime.time(6, 0))),
                ('zuhur', models.TimeField(default=datetime.time(6, 0))),
                ('asar', models.TimeField(default=datetime.time(6, 0))),
                ('maghrib', models.TimeField(default=datetime.time(6, 0))),
                ('isha', models.TimeField(default=datetime.time(6, 0))),
                ('date_time_parsed', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(default='202.75.5.204', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_times', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('did_autolocate', models.BooleanField(default=False)),
                ('esolat_zone', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parsed_zone', to='azanlocator.EsolatZone')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=10)),
                ('master_schedule', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='azanlocator.MasterSchedule')),
            ],
        ),
        migrations.AddField(
            model_name='parsedtimes',
            name='zone',
            field=models.ForeignKey(default=azanlocator.models.init_zone_code, on_delete=django.db.models.deletion.CASCADE, related_name='parsed_times', to='azanlocator.ParsedZone'),
        ),
        migrations.AddField(
            model_name='dailytimes',
            name='zone_times',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='azanlocator.ZoneTimes'),
        ),
    ]
