# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:06
from __future__ import unicode_literals

import azanlocator.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField(default=django.utils.timezone.now)),
                ('subuh', models.TimeField(default=datetime.time(6, 0))),
                ('syuruk', models.TimeField(default=datetime.time(6, 0))),
                ('zuhur', models.TimeField(default=datetime.time(6, 0))),
                ('asar', models.TimeField(default=datetime.time(6, 0))),
                ('maghrib', models.TimeField(default=datetime.time(6, 0))),
                ('isha', models.TimeField(default=datetime.time(6, 0))),
            ],
        ),
        migrations.CreateModel(
            name='EsolatZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='KUALA LUMPUR', max_length=30)),
                ('zone_name', models.CharField(default='Kuala Lumpur', max_length=30)),
                ('code_name', models.CharField(default='SGR03', max_length=20)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subuh', models.TimeField(default=datetime.time(6, 0))),
                ('syuruk', models.TimeField(default=datetime.time(6, 0))),
                ('zuhur', models.TimeField(default=datetime.time(6, 0))),
                ('asar', models.TimeField(default=datetime.time(6, 0))),
                ('maghrib', models.TimeField(default=datetime.time(6, 0))),
                ('isha', models.TimeField(default=datetime.time(6, 0))),
                ('date_time_parsed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='KUALA LUMPUR', max_length=30)),
                ('zone_name', models.CharField(default='Kuala Lumpur', max_length=30)),
                ('ip_address', models.CharField(default='202.75.5.204', max_length=20)),
                ('ip_parse_str', models.CharField(default='{"country_name": "United States", "metro_code": 501, "region_name": "New York", "ip": "108.46.131.77", "country_code": "US", "region_code": "NY", "time_zone": "America/New_York", "latitude": 40.645, "longitude": -73.945, "zip_code": "11249", "city": "Brooklyn"}', max_length=400)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('raw_solat_parse', models.CharField(default='nothing', max_length=400)),
                ('esolat_zone', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='azanlocator.EsolatZone')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=10)),
                ('daily_times', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='azanlocator.DailyTimes')),
            ],
        ),
        migrations.AddField(
            model_name='parsedtimes',
            name='zone',
            field=models.ForeignKey(default=azanlocator.models.init_zone_code, on_delete=django.db.models.deletion.CASCADE, to='azanlocator.ParsedZone'),
        ),
        migrations.AddField(
            model_name='masterschedule',
            name='zones_times',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='azanlocator.ZoneTimes'),
        ),
    ]
