# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azanlocator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedzone',
            name='ip_parse_str',
            field=models.CharField(default='{"longitude": -73.945, "time_zone": "America/New_York", "metro_code": 501, "city": "Brooklyn", "zip_code": "11249", "ip": "108.46.131.77", "region_name": "New York", "country_name": "United States", "country_code": "US", "latitude": 40.645, "region_code": "NY"}', max_length=400),
        ),
    ]
