# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azanlocator', '0002_auto_20170201_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedzone',
            name='ip_parse_str',
            field=models.CharField(default='{"city": "Brooklyn", "zip_code": "11249", "region_code": "NY", "time_zone": "America/New_York", "region_name": "New York", "ip": "108.46.131.77", "country_name": "United States", "metro_code": 501, "country_code": "US", "latitude": 40.645, "longitude": -73.945}', max_length=400),
        ),
    ]
