# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azanlocator', '0004_auto_20170201_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedzone',
            name='ip_parse_str',
            field=models.CharField(default='{"country_code": "US", "country_name": "United States", "latitude": 40.645, "time_zone": "America/New_York", "metro_code": 501, "zip_code": "11249", "longitude": -73.945, "region_code": "NY", "city": "Brooklyn", "region_name": "New York", "ip": "108.46.131.77"}', max_length=400),
        ),
    ]
