# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('azanlocator', '0005_auto_20170201_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterschedule',
            name='zones_times',
        ),
        migrations.RemoveField(
            model_name='zonetimes',
            name='daily_times',
        ),
        migrations.AddField(
            model_name='dailytimes',
            name='zone_times',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='azanlocator.ZoneTimes'),
        ),
        migrations.AddField(
            model_name='masterschedule',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='zonetimes',
            name='master_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='azanlocator.MasterSchedule'),
        ),
        migrations.AlterField(
            model_name='parsedzone',
            name='ip_parse_str',
            field=models.CharField(default='{"metro_code": 501, "zip_code": "11249", "ip": "108.46.131.77", "region_code": "NY", "longitude": -73.945, "time_zone": "America/New_York", "country_code": "US", "region_name": "New York", "country_name": "United States", "city": "Brooklyn", "latitude": 40.645}', max_length=400),
        ),
    ]
