# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azanlocator', '0006_auto_20170201_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedzone',
            name='ip_parse_str',
            field=models.CharField(default='{"metro_code": 501, "region_name": "New York", "country_name": "United States", "zip_code": "11249", "country_code": "US", "latitude": 40.645, "region_code": "NY", "longitude": -73.945, "city": "Brooklyn", "ip": "108.46.131.77", "time_zone": "America/New_York"}', max_length=400),
        ),
    ]
