# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azanlocator', '0007_auto_20170201_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedzone',
            name='ip_parse_str',
            field=models.CharField(default='{"longitude": -73.945, "city": "Brooklyn", "time_zone": "America/New_York", "latitude": 40.645, "region_name": "New York", "region_code": "NY", "zip_code": "11249", "ip": "108.46.131.77", "metro_code": 501, "country_code": "US", "country_name": "United States"}', max_length=400),
        ),
    ]
