# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 09:21
from __future__ import unicode_literals

import azanlocator.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azanlocator', '0009_auto_20170201_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedzone',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='parsedtimes',
            name='ip_address',
            field=models.CharField(default='202.75.5.204', max_length=20),
        ),
        migrations.AlterField(
            model_name='parsedtimes',
            name='zone',
            field=models.ForeignKey(default=azanlocator.models.init_zone_code, on_delete=django.db.models.deletion.CASCADE, related_name='parsed_times', to='azanlocator.ParsedZone'),
        ),
        migrations.AlterField(
            model_name='parsedzone',
            name='esolat_zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parsed_zone', to='azanlocator.EsolatZone'),
        ),
    ]
