# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azanlocator', '0010_auto_20170202_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedzone',
            name='did_autolocate',
            field=models.BooleanField(default=False),
        ),
    ]
